import {createAsyncThunk, createSlice, PayloadAction} from '@reduxjs/toolkit';
import {RootState} from './store';
import {Champ, getChampList} from "../services/ddragon.service";

export interface DdragonState {
    champs: Champ[];
    status: 'idle' | 'loading' | 'failed';
}

const initialState: DdragonState = {
    champs: [],
    status: 'idle',
};

export const fetchChampList = createAsyncThunk('fetchChampList', async (_, { rejectWithValue } ) => {
    try {
        const champs = await getChampList();
        return champs.sort((a,b) => a.name.localeCompare(b.name));
    } catch(e) {
        rejectWithValue(e);
    }
});


export const ddragonSlice = createSlice({
    name: 'ddragon',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setChamps: (state, action: PayloadAction<Champ[]>) => {
            state.champs = action.payload;
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchChampList.rejected, (state, { error }) => {
                console.log(error);
            })
            .addCase(fetchChampList.fulfilled, (state, action: PayloadAction<Champ[] | undefined>) => {
                state.champs = action.payload!;
            })
    },
});

export const { setChamps } = ddragonSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectChamps = (state: RootState) => state.ddragon.champs;

export default ddragonSlice.reducer;
